package online.qsx.mapper;

import java.util.List;
import online.qsx.model.AboutMe;
import online.qsx.model.AboutMeCriteria;
import org.apache.ibatis.annotations.Param;

public interface AboutMeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_about_me
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int countByExample(AboutMeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_about_me
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int deleteByExample(AboutMeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_about_me
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_about_me
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int insert(AboutMe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_about_me
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int insertSelective(AboutMe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_about_me
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    List<AboutMe> selectByExample(AboutMeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_about_me
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    AboutMe selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_about_me
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") AboutMe record, @Param("example") AboutMeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_about_me
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int updateByExample(@Param("record") AboutMe record, @Param("example") AboutMeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_about_me
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int updateByPrimaryKeySelective(AboutMe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_about_me
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int updateByPrimaryKey(AboutMe record);
}