package online.qsx.mapper;

import java.util.List;
import online.qsx.model.EducationDegree;
import online.qsx.model.EducationDegreeCriteria;
import org.apache.ibatis.annotations.Param;

public interface EducationDegreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_education_degree
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int countByExample(EducationDegreeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_education_degree
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int deleteByExample(EducationDegreeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_education_degree
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_education_degree
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int insert(EducationDegree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_education_degree
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int insertSelective(EducationDegree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_education_degree
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    List<EducationDegree> selectByExample(EducationDegreeCriteria example);
    List<EducationDegree> selectByLanguage(Integer tAboutMeId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_education_degree
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    EducationDegree selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_education_degree
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") EducationDegree record, @Param("example") EducationDegreeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_education_degree
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int updateByExample(@Param("record") EducationDegree record, @Param("example") EducationDegreeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_education_degree
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int updateByPrimaryKeySelective(EducationDegree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_education_degree
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int updateByPrimaryKey(EducationDegree record);
}