package online.qsx.mapper;

import java.util.List;
import online.qsx.model.WorkingStatus;
import online.qsx.model.WorkingStatusCriteria;
import org.apache.ibatis.annotations.Param;

public interface WorkingStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_working_status
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int countByExample(WorkingStatusCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_working_status
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int deleteByExample(WorkingStatusCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_working_status
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_working_status
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int insert(WorkingStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_working_status
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int insertSelective(WorkingStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_working_status
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    List<WorkingStatus> selectByExample(WorkingStatusCriteria example);
    List<WorkingStatus> selectByLanguage(Integer tAboutMeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_working_status
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    WorkingStatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_working_status
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") WorkingStatus record, @Param("example") WorkingStatusCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_working_status
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int updateByExample(@Param("record") WorkingStatus record, @Param("example") WorkingStatusCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_working_status
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int updateByPrimaryKeySelective(WorkingStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_working_status
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    int updateByPrimaryKey(WorkingStatus record);
}