package online.qsx.model;

import java.io.Serializable;
import java.util.Date;

public class AboutMe implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_about_me.id
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_about_me.name
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_about_me.gender
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_about_me.birthday
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_about_me.motto
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    private String motto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_about_me.residence
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    private String residence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_about_me.email
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_about_me.mobile
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_about_me.language
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_about_me.createTime
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_about_me.workingYears
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    private String workingyears;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_about_me.resumeFile
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    private String resumefile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_about_me
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_about_me.id
     *
     * @return the value of t_about_me.id
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_about_me.id
     *
     * @param id the value for t_about_me.id
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_about_me.name
     *
     * @return the value of t_about_me.name
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_about_me.name
     *
     * @param name the value for t_about_me.name
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_about_me.gender
     *
     * @return the value of t_about_me.gender
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_about_me.gender
     *
     * @param gender the value for t_about_me.gender
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_about_me.birthday
     *
     * @return the value of t_about_me.birthday
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_about_me.birthday
     *
     * @param birthday the value for t_about_me.birthday
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_about_me.motto
     *
     * @return the value of t_about_me.motto
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public String getMotto() {
        return motto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_about_me.motto
     *
     * @param motto the value for t_about_me.motto
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public void setMotto(String motto) {
        this.motto = motto == null ? null : motto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_about_me.residence
     *
     * @return the value of t_about_me.residence
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public String getResidence() {
        return residence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_about_me.residence
     *
     * @param residence the value for t_about_me.residence
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public void setResidence(String residence) {
        this.residence = residence == null ? null : residence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_about_me.email
     *
     * @return the value of t_about_me.email
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_about_me.email
     *
     * @param email the value for t_about_me.email
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_about_me.mobile
     *
     * @return the value of t_about_me.mobile
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_about_me.mobile
     *
     * @param mobile the value for t_about_me.mobile
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_about_me.language
     *
     * @return the value of t_about_me.language
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_about_me.language
     *
     * @param language the value for t_about_me.language
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_about_me.createTime
     *
     * @return the value of t_about_me.createTime
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_about_me.createTime
     *
     * @param createtime the value for t_about_me.createTime
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_about_me.workingYears
     *
     * @return the value of t_about_me.workingYears
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public String getWorkingyears() {
        return workingyears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_about_me.workingYears
     *
     * @param workingyears the value for t_about_me.workingYears
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public void setWorkingyears(String workingyears) {
        this.workingyears = workingyears == null ? null : workingyears.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_about_me.resumeFile
     *
     * @return the value of t_about_me.resumeFile
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public String getResumefile() {
        return resumefile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_about_me.resumeFile
     *
     * @param resumefile the value for t_about_me.resumeFile
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public void setResumefile(String resumefile) {
        this.resumefile = resumefile == null ? null : resumefile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_about_me
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", gender=").append(gender);
        sb.append(", birthday=").append(birthday);
        sb.append(", motto=").append(motto);
        sb.append(", residence=").append(residence);
        sb.append(", email=").append(email);
        sb.append(", mobile=").append(mobile);
        sb.append(", language=").append(language);
        sb.append(", createtime=").append(createtime);
        sb.append(", workingyears=").append(workingyears);
        sb.append(", resumefile=").append(resumefile);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}