package online.qsx.model;

import java.io.Serializable;

public class EducationDegree implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_education_degree.id
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_education_degree.name
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_education_degree.t_about_me_id
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    private Integer tAboutMeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_education_degree.Date
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_education_degree.vocational
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    private String vocational;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_education_degree
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_education_degree.id
     *
     * @return the value of t_education_degree.id
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_education_degree.id
     *
     * @param id the value for t_education_degree.id
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_education_degree.name
     *
     * @return the value of t_education_degree.name
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_education_degree.name
     *
     * @param name the value for t_education_degree.name
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_education_degree.t_about_me_id
     *
     * @return the value of t_education_degree.t_about_me_id
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public Integer gettAboutMeId() {
        return tAboutMeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_education_degree.t_about_me_id
     *
     * @param tAboutMeId the value for t_education_degree.t_about_me_id
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public void settAboutMeId(Integer tAboutMeId) {
        this.tAboutMeId = tAboutMeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_education_degree.Date
     *
     * @return the value of t_education_degree.Date
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_education_degree.Date
     *
     * @param date the value for t_education_degree.Date
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_education_degree.vocational
     *
     * @return the value of t_education_degree.vocational
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public String getVocational() {
        return vocational;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_education_degree.vocational
     *
     * @param vocational the value for t_education_degree.vocational
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public void setVocational(String vocational) {
        this.vocational = vocational == null ? null : vocational.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_education_degree
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", tAboutMeId=").append(tAboutMeId);
        sb.append(", date=").append(date);
        sb.append(", vocational=").append(vocational);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}