package online.qsx.model;

import java.io.Serializable;

public class WorkingStatus implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_working_status.id
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_working_status.name
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_working_status.date
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_working_status.mission
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    private String mission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_working_status.job
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_working_status.t_about_me_id
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    private Integer tAboutMeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_working_status
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_working_status.id
     *
     * @return the value of t_working_status.id
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_working_status.id
     *
     * @param id the value for t_working_status.id
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_working_status.name
     *
     * @return the value of t_working_status.name
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_working_status.name
     *
     * @param name the value for t_working_status.name
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_working_status.date
     *
     * @return the value of t_working_status.date
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_working_status.date
     *
     * @param date the value for t_working_status.date
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_working_status.mission
     *
     * @return the value of t_working_status.mission
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public String getMission() {
        return mission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_working_status.mission
     *
     * @param mission the value for t_working_status.mission
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public void setMission(String mission) {
        this.mission = mission == null ? null : mission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_working_status.job
     *
     * @return the value of t_working_status.job
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_working_status.job
     *
     * @param job the value for t_working_status.job
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_working_status.t_about_me_id
     *
     * @return the value of t_working_status.t_about_me_id
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public Integer gettAboutMeId() {
        return tAboutMeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_working_status.t_about_me_id
     *
     * @param tAboutMeId the value for t_working_status.t_about_me_id
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    public void settAboutMeId(Integer tAboutMeId) {
        this.tAboutMeId = tAboutMeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_working_status
     *
     * @mbggenerated Wed Jan 24 10:11:36 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", date=").append(date);
        sb.append(", mission=").append(mission);
        sb.append(", job=").append(job);
        sb.append(", tAboutMeId=").append(tAboutMeId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}